language: generic

services:
  - docker

env:
  - CONFIGURE_FLAGS=
  - CONFIGURE_FLAGS=--release
  - CONFIGURE_FLAGS=--no-debug

before_install:
  - export CONTAINER_ID=$(docker run -itd --rm --mount type=bind,source="$(pwd)",target=/app debian:stable)
  - docker exec $CONTAINER_ID sh -c 'echo "deb http://deb.debian.org/debian stable-backports main" > /etc/apt/sources.list.d/backports.list'
  - docker exec $CONTAINER_ID apt-get update
  - docker exec $CONTAINER_ID apt-get install -y build-essential gettext cmake valac libgee-0.8-dev libsqlite3-dev libgtk-3-dev libnotify-dev libgpgme-dev libsoup2.4-dev libgcrypt20-dev libqrencode-dev libhandy-1-dev

install:
  - docker exec $CONTAINER_ID bash -c "cd /app; ./configure --with-tests --with-libsignal-in-tree $CONFIGURE_FLAGS"
  - docker exec $CONTAINER_ID bash -c "cd /app; make"

script:
  - docker exec $CONTAINER_ID bash -c "cd /app; build/xmpp-vala-test"
  - docker exec $CONTAINER_ID bash -c "cd /app; build/signal-protocol-vala-test"

after_script:
  - docker kill $CONTAINER_ID
